/**
 * @file mtUnitLogger.h
 * @author Rodrigo Haller
 * @date 24/02/2018
 * @brief Hijacks the LogFile and add colors to the output.
 * @details This class looks for the output log file generated by MetaEditor,
 * hijacks this file to the Runners folder and adds some color to the output
 * to make it more visual effective.
 * @note In order to use this class, the argument received by mtUnitHelper.exe
 * must be: mtUnitLogger
 * @warning The colored output does not work directly from MetaEditor, so if
 * you want to use it, I suggest you to follow the instructions for using this
 * tool in Sublime Text 3.
 */

#ifndef MTUNITLOGGER_H
#define MTUNITLOGGER_H

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QDateTime>
#include <QString>
#include <QDebug>

class MTUnitLogger
{
public:
    MTUnitLogger(){}
    ~MTUnitLogger(){}

    int start(QString rootDir);
};

#endif // MTUNITLOGGER_H
